PROJECT_NAME_INPUT_FIELD_KEY = "-PROJECT_NAME_INPUT_FIELD_KEY-"

BROWSE_FILE_BUTTON_TEXT = "Browse"
SUBMIT_BUTTON_TEXT = "Submit"
EXIT_BUTTON_TEXT = "Exit"

INPUT_FOLDER_DIRECTORY_INPUT_KEY = "-INPUT_FOLDER_DIRECTORY_INPUT_KEY-"
BROWSE_INPUT_FOLDER_BUTTON_KEY = "-BROWSE_INPUT_FOLDER_BUTTON-"

OUTPUT_FOLDER_NAME_INPUT_KEY = "-OUTPUT_FOLDER_NAME_INPUT-"
OUTPUT_FOLDER_DIRECTORY_INPUT_KEY = "-OUTPUT_FOLDER_DIRECTORY_INPUT-"
BROWSE_OUTPUT_FOLDER_BUTTON_KEY = "-BROWSE_OUTPUT_FOLDER_BUTTON-"

OUTPUT_CSV_FOLDER_DIRECTORY_INPUT_KEY = "-OUTPUT_CSV_FOLDER_DIRECTORY_INPUT-"
BROWSE_OUTPUT_CSV_FOLDER_BUTTON_KEY = "-BROWSE_OUTPUT_CSV_FOLDER_BUTTON-"


THRESHOLD_INPUT_FIELD_KEY = "-THRESHOLD_INPUT_FIELD-"

USE_WHITELIST_KEY = "-USE_WHITELIST-"
ENTER_WHITELIST_TEXT_KEY = "-ENTER_WHITELIST_TEXT-"
WHITELIST_INPUT_FIELD_KEY = "-WHITELIST_INPUT_FIELD-"

USE_BLACKLIST_KEY = "-USE_BLACKLIST-"
ENTER_BLACKLIST_TEXT_KEY = "-ENTER_BLACKLIST_TEXT-"
BLACKLIST_INPUT_FIELD_KEY = "-BLACKLIST_INPUT_FIELD-"

PROGRESS_BAR_KEY = '-PROGRESS_BAR_KEY-'
PROGRESS_PERCENTAGE_KEY = '-PROGRESS_PERCENTAGE_KEY-'
ESTIMATED_REMAINING_TIME_KEY = '-ESTIMATED_REMAINING_TIME_KEY-'
EXCHANGE_MESSGES_TEXT_KEY = "-EXCHANGE_MESSGES_TEXT_KEY-"

INPUT_CSV_FILE_PATH_INPUT_KEY = "-INPUT_CSV_FILE_PATH_INPUT_KEY-"
BROWSE_INPUT_CSV_FILE_BUTTON_KEY = "-BROWSE_INPUT_CSV_FILE_BUTTON-"
FILE_PATH_KEY = "-FILE-"
BROWSE_FILE_BUTTON_TEXT = "Browse"
SUBMIT_BUTTON_TEXT = "Submit"
EXIT_BUTTON_TEXT = "Exit"
RUN_PAUSE_BUTTON_KEY = '-RUN-PAUSE-'

CSV_TABLE_KEY = "-CSV_TABLE-"
FIRST_ROW_IS_HEADER_KEY = "-FIRST_ROW_IS_HEADER-"
DELIMITER_IS_COMMA_KEY = "-RADIO_CSV_DELIMITER_IS_COMMA-"
DELIMITER_IS_SEMICOLON_KEY = "-RADIO_CSV_DELIMITER_IS_SEMICOLON-"

MRN_COLUMN_NAME_INPUT_FIELD_KEY = "-MRN_COLUMN_NAME_INPUT_FIELD_KEY-"
ACCESSION_NUMBER_COLUMN_NAME_INPUT_FIELD_KEY = "-ACCESSION_NUMBER_COLUMN_NAME_INPUT_FIELD_KEY-"

INPUT_CSV_FILE_PATH_OUTPUT_KEY = "-INPUT_CSV_FILE_PATH_OUTPUT_KEY-"
BROWSE_INPUT_CSV_FILE_OUTPUT_BUTTON_KEY = "-BROWSE_INPUT_CSV_FILE_OUTPUT_BUTTON-"

OUTPUT_CSV_FILE_PATH_OUTPUT_KEY = "-OUTPUT_CSV_FILE_PATH_OUTPUT_KEY-"
BROWSE_OUTPUT_CSV_FILE_BUTTON_KEY = "-BROWSE_OUTPUT_CSV_FILE_BUTTON-"