BROWSE_FILE_BUTTON_TEXT = "Browse"
SUBMIT_BUTTON_TEXT = "Submit"
EXIT_BUTTON_TEXT = "Exit"

INPUT_FOLDER_DIRECTORY_INPUT_KEY = "-INPUT_FOLDER_DIRECTORY_INPUT_KEY-"
BROWSE_INPUT_FOLDER_BUTTON_KEY = "-BROWSE_INPUT_FOLDER_BUTTON-"
CONTENT_OF_A_FOLDER_BELONGS_TO_SAME_STUDY_CHECKBOX_KEY = "-CONTENT_OF_A_FOLDER_BELONGS_TO_SAME_STUDY_CHECKBOX_KEY-"

OUTPUT_FOLDER_NAME_INPUT_KEY = "-OUTPUT_FOLDER_NAME_INPUT-"
OUTPUT_FOLDER_DIRECTORY_INPUT_KEY = "-OUTPUT_FOLDER_DIRECTORY_INPUT-"
BROWSE_OUTPUT_FOLDER_BUTTON_KEY = "-BROWSE_OUTPUT_FOLDER_BUTTON-"

PROGRESS_BAR_KEY = '-PROGRESS_BAR_KEY-'
PROGRESS_PERCENTAGE_KEY = '-PROGRESS_PERCENTAGE_KEY-'
ESTIMATED_REMAINING_TIME_KEY = '-ESTIMATED_REMAINING_TIME_KEY-'
EXCHANGE_MESSGES_TEXT_KEY = "-EXCHANGE_MESSGES_TEXT_KEY-"